### ISSUE TITLE
Fix: 배포를 위한 yml 분리 및 오류 수정

### ISSUE THREAD

**Issue by lcomment** [CAFREE-dev/cafree-backend#37]
## Description

> 백엔드 배포를 위해 yml 설정파일을 production, develop, test로 분리하고, security 설정으로 인한 테스트 코드 오류를 수정한다.

## Code To Request

**Prev**
```yml
# application.yml
spring:
  datasource:
    . . .

cloud:
  aws:
    . . .
```

**Fixed**
```yml
# application.yml
spring:
  profiles:
     active: prod

---

spring: 
   profiles
      . . .

```
